### PR TITLE
Handle missed offline messages as new chat messages

### PR DESCRIPTION
**Pull request by softashell**
Use RequestOfflineMessages to get them

### CODE REVIEW

**Comment by Philipp15b** [comment]
Would it be possible to add the time of the message to the ChatMsgEvent? That way offline messages and new messages can be distinguished.

**Comment by softashell** [comment]
Normal chat messages include timestamp as well, so I guess it can be added for both or just make seperate event for offline messages

https://github.com/Philipp15b/go-steam/blob/master/protocol/protobuf/client_server.pb.go#L8392

**Comment by softashell** [comment]
Only unique thing to offline message is unread status, which is always true if message isn't just chat history.

https://github.com/Philipp15b/go-steam/blob/master/protocol/protobuf/client_server_2.pb.go#L5404

**Comment by Philipp15b** [comment]
That's exactly what I had in mind.
If I may ask for another addition, do you know which format the timestamp is in? Because I think setting the timestamp's type to be `time.Time` instead of a number makes usage much clearer. It would probably be a unix timestamp, so wrapping it with `time.Unix` should be enough.

**Comment by Philipp15b** [comment]
Thank you!

**Pull request merged**
