### PR TITLE
Fix tradeoffer accept

### PR DESCRIPTION
**Pull request by TwinkerMan**

### CODE REVIEW

**Comment by b1naryth1ef** [comment]
Why change the original structure around the usage of `baseurl`? Also can you give a reason as to removing `tradeofferid` from the params? AFAIK this is still required.

**Comment by TwinkerMan** [comment]
tradeofferid don't required because tradeofferid stay in URL

Bot log (MSK time):
2015/06/17 13:42:26 Connected
2015/06/17 13:42:26 Loggind on
2015/06/17 13:42:27 Logged on
2015/06/17 13:42:28 Web logging on
2015/06/17 13:42:29 Successfully logged on web
2015/06/17 13:42:30 Processing TOffer with ID 532196644
2015/06/17 13:42:30 Processing TOffer with ID 532196265
2015/06/17 13:42:30 Processing TOffer with ID 532196010
2015/06/17 13:42:35 TradeOfferId 532196010 accepted (FrontEnd REST API confirm).
2015/06/17 13:42:37 TradeOfferId 532196265 accepted (FrontEnd REST API confirm).
2015/06/17 13:42:42 TradeOfferId 532196644 accepted (FrontEnd REST API confirm).

Steam (MSK time):
Trade Accepted 17 Jun, 2015 @ 1:42pm
Trade Accepted 17 Jun, 2015 @ 1:42pm
Trade Accepted 17 Jun, 2015 @ 1:42pm

**Comment by Philipp15b** [comment]
So your fix basically consists of removing the `tradeofferid` parameter? An additional parameter shouldn't be a problem. Moreover, I can't find evidence elsewhere that Steam now rejects that parameter; [node-steam-tradeoffers](https://github.com/Alex7Kom/node-steam-tradeoffers) for example still sends it and [SteamBot](https://github.com/Jessecar96/SteamBot) does too. Finally, Valve itself sends it in their [`economy_tradeoffer.js`](https://github.com/SteamDatabase/SteamTracking/blob/5cc203bc1bfa1c326e13cdf57fb9ea002a790b9c/Scripts/Community/economy_tradeoffer.js#L595) via their web interface.

Have you considered the API temporarily not working? From what I've seen, that's quite common with Valve APIs.

**Comment by Philipp15b** [comment]
This

**Pull request closed without merging**
