### PR TITLE
Code review

### PR DESCRIPTION
**Pull request by vvekic**
Revised import statements across the whole project.
Guidelines: https://github.com/golang/go/wiki/CodeReviewComments#import-dot

The dot imports have rendered this project completely unreadable.
Excessive verbosity has to be solved by other means of refactoring/restructuring/renaming. Dot imports are not a good solution.

This change adds to clarity and separation of namespaces.

### CODE REVIEW

**Comment by Philipp15b** [comment]
I don't agree at all. With some understanding of the project's structure, you can see that all types can be easily identified as belonging to a certain package:

- `SteamId` obviously lives in the `steamid` package; if it weren't for Go's inability to handle cyclic dependencies it would be part of the `steam` package anyway
- `CMsg*` types are protobuf messages
- `EMsg*` types are struct messages living in the `steamlang` package
- everything else is in `protocol`

That mirrors SteamKit's behavior where, by the way, such imports are used all over the place - as is common C# and many other languages. They're not "completely unreadable" at all. Maybe it's godoc you're really concerned about because it still doesn't handle dot imports, but I see that as a bug of godoc not implementing the Go spec. I'm not willing to litter the code with unnecessary repetitions only to work around a broken tool.

This verbosity is not an improvement. You're giving the recommendation to refactor the project, but that is not a concrete solution.

I'll leave this open for further discussion.

**Comment by vvekic** [comment]
I understand there is structure in the naming of different types, but i still strongly feel packages can and should be naturally used as namespaces in Go, and I fail to see how identifier name prefixes such as CMsg or EMsg can be more adequate. In other words - the fact you or me can understand what those prefixes represent doesn't really justify the practice. Neither does the fact that SteamKit behaves similarly.

I was entirely unconcerned with godoc.
The dot imports are to be used to resolve cyclic dependencies that can arise in certain types of tests only.

Verbosity not an improvement per se when it brings with it no extra information. In this case it brings critical information, and I still believe it is an improvement. The generated code can also be further simplified and the verbosity reduced. I will be working on that in my fork and maybe you'll be convinced with a future commit.

P.S.
Can you elaborate on the SteamId cyclic dependency issue? I see the `steamid` package only imports packages from the standard library.

**Comment by Tommy-42** [comment]
I kinda join @vvekic on that.

( bare with me am gonna use a keyword here ) 
it feels more **go idiomatic** to have import with package rather than to use the dot import.

while working on #120 I had hard time figuring out what or where thing were needed / used.
so for a better understanding import with package feels better ( for me ). 

You can have a look at the `Effective Go` https://golang.org/doc/effective_go#package-names
I guess it is not a best practice from the go perspective to use the dot notation.

**Comment by Philipp15b** [comment]
Yes, I eventually agreed on the dot imports :) However, they should have been removed in https://github.com/Philipp15b/go-steam/pull/117 right? As this pull request is pretty old now and has lots of conflicts, I'll close it. If there are dot imports or other improvements, feel free to comment/open another issue.

**Pull request closed without merging**
