### PR TITLE
Fix module paths - Fixes #115

### LINKED ISSUE #115: Wrong module path in go.mod
As per documention:
> If the module is released at major version 2 or higher, the module path must end with a major version suffix

Since go-steam has `go.mod` file at git tag `v2.0.0` it must have `module github.com/Philipp15b/go-steam/v2` in `go.mod` and not `module github.com/Philipp15b/go-steam`.

Because of that it cannot be shown in htttps://pkg.go.dev/ for example.

### PR DESCRIPTION
**Pull request by Jleagle**
I could remove all the dot import aliases too if you like as they are not recommended.

@gudvinr, could you check this over pease.

### CODE REVIEW

**Comment by Philipp15b** [comment]
Thanks a bunch! I assume `steamid.go` had wrong line endings or why was the whole file changed?

I'll also happily accept another PR to remove dot imports. That might be a bit more difficult though as the generator must be adapted as well.

**Comment by Jleagle** [comment]
Yep, assumed it was line endings, let me know if you want me to revert the file.

**Comment by gudvinr** [comment]
> Thanks a bunch! I assume `steamid.go` had wrong line endings or why was the whole file changed?

You can use `.gitattributes` or `core.eol` option for git and it'lll convert automatically.

**Comment by Philipp15b** [comment]
Thanks @Jleagle!

**Pull request merged**
